### ISSUE TITLE
Determine lbry.lat homepage (Anabell + Socrates)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-latam#1]
What should be displayed by default?

**Comment by kauffj** [comment]
@jessopb can you please link or write a short explanation for @michaelmitnick on how he can control this?

**Comment by michaelmitnick** [comment]
Yes please, I want to organize myself well with this. Thank you. @jessopb @kauffj

**Comment by jessopb** [comment]
Hello @michaelmitnick 
I've included some documentation in the README.md and some example code in the defaults:
https://github.com/lbryio/lbry-desktop/blob/f5805721e7ea50fd74f8ba952c8b9552095de503/.env.defaults#L1

Start off by customizing these in the new .env

`DOMAIN=lbry.tv
URL=https://lbry.tv
SITE_TITLE=lbry.tv
LOGO_TITLE=LBRY`

And there are examples here to help you fill out your homepage:
github.com/lbryio/lbry-desktop/blob/f5805721e7ea50fd74f8ba952c8b9552095de503/custom/homepage.example.js#L4

Let me know how it goes

**Comment by michaelmitnick** [comment]
Perfect, thanks for the information. I am going to organize all my work environment to carry out the processes.

**Comment by michaelmitnick** [comment]
Hello @jessopb, I have been reinstalling the entire operating system again (Linux Mint) to work cleanly. I use Windows and Linux Mint, but I just want to set LBRY development from Linux. Here is a screenshot of the entire compilation procedure and result on localhost. The .env file automatically displayed the data, although I did see some errors during some compilations, perhaps some dependencies.

Whats Next?

![image.png](https://images.zenhubusercontent.com/5ec4524cfc2bed7634736fcc/421c7c37-bc03-495a-b065-4a5705dc937c)

**Comment by kauffj** [comment]
@michaelmitnick that appears to be correct. Were you able to edit the file and/or make changes and see them?

**Comment by michaelmitnick** [comment]
Hello @kauffj, I was waiting for a particular task to make changes to a file. Maybe I didn't get it right at first when they submitted the assignment, but I'm going to test a few edits to see the results. Once you understand the structure it will be much easier. I'm going to do the tagging to see how it works. I'll be at it. :)

**Comment by michaelmitnick** [comment]
All right. I did a fork of and then a PR. This is correct? https://github.com/michaelmitnick/lbry-redux/commit/c7de10be2df2f6ec3e8091c288ef0899954d25d6 @jessopb @kauffj

**Comment by michaelmitnick** [comment]
Hello one question. The changes I am making in lbry-desktop are to fork in GitHub when I do the pull request or are they for the lbry-latam repository? It is to know to which repository I should direct the pull requests. :) @jessopb

**Comment by jessopb** [comment]
@michaelmitnick I DM'd you on discord
