### ISSUE TITLE
Give lbry.lat retention data

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-latam#20]

**Comment by kauffj** [comment]
@lyoshenka consider that new retention tracking system should allow us to deliver reports regarding independent app experiences to other communities.

**Comment by lyoshenka** [comment]
In my system lbry.lat would have to be its own segment.

If this is more about "how do we let non-employees see retention data", that part is pretty simple. The API to get the data will be part of internal apis, so we can use the same permissions system we already have.

**Comment by lyoshenka** [comment]
Can you give me the query for the lbry.lat segment? I'll try it out.

**Comment by kauffj** [comment]
It would be users with an entry in the install table for lbry.lat

**Comment by kauffj** [comment]
@tzarebczan is there an elevated permission required to see the list of tags for retention?

**Comment by kauffj** [comment]
https://commander.lbry.com/retention?tag=segment-lbrylat-reward-approved&interval=weekly&since=2020-01-31
https://commander.lbry.com/retention?tag=segment-lbrylat&interval=weekly&since=2020-01-01
