### ISSUE TITLE
Do list building for best channels for Latam brand

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-latam#22]
- 3-5 categories
- 10-50 channels in each category (at least some channels need to publish regularly)
- Can also list channels not on LBRY that would be strong fit for a category

**Comment by gutss** [comment]
https://docs.google.com/spreadsheets/d/1CV_mChjiZXOI3L43weefVUSVM67uHAFXyfVgmGs2fM0/edit#gid=764867374

**Comment by kauffj** [comment]
Categories need ~15 channels to be viable
