### ISSUE TITLE
Give lbry.lat ongoing access to Latin American creators joining LBRY

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-latam#29]
@tzarebczan discuss with me how we can do this

**Comment by tzarebczan** [comment]
We'd probably need to use chainquery data to check the published language of content. To do this, we'd need CQ data available on sql.lbry.tech to join with internal apis data. @nikooo777 is aware of this gap. 

Or we can start saving language data on publish table...

**Comment by kauffj** [comment]
@tzarebczan could we do content by views but only from lbry.lat?

**Comment by tzarebczan** [comment]
Yea, we can do something like that in the meantime. WIll get a report together!

**Comment by tzarebczan** [comment]
Here's the first report for based on content: https://traction.lbry.com/public/question/121eae71-6f91-4c8a-bdc4-0cb74dbbe4af

Will do another channel based one.

**Comment by tzarebczan** [comment]
Here's one at a channel view : https://traction.lbry.com/question/446?last_n_days=7&total_lbc=10&tag=lbry.lat 

Added a filter for channel age that's optional (set to 9999 by default) for exploring newer channels. 

Also added filter to both for lbry.lat / lbry.lat-exclusive (default to lbry.lat) - exclusive not working yet.
